version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_ROOT_PASSWORD: Siva@2000

  spring_boot_app:
      build:
        context: ./Cryptocurrency-Management-System-Backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/crypto
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Siva@2000
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        SPRING_JPA_SHOW_SQL: "true"

  react_app:
      build:
        context: ./Crypto-Currency-Management-System
        dockerfile: Dockerfile
      ports:
        - "3000:80"